Scouterna/skojjt

templates/troop.html

Vad tror du om att ha utökad information om man hoverar på saker i troop-vyn:
* Tid för mötet
* Fullständigt namn
* Dag och Namn för checkboxar

Title-text on elements on Troops page

---

templates/sensusnarvaro.html

Do not use flex. Removed unused styling. #41 
Has not been tested with data - I have no running environment.
Please test before merge.

Simplified table to work in more browsers

---

index.yaml
sensus.py

Är osäker på om index.yaml skall med, men den autouppdateras när jag kör lokalt.

#46 Summera lektionstimmar korrekt

---

js/csv_table_2_href.ts
templates/troop.html

Add a "Export XLS" and a "Export CSV" in troop page

xls and csv export from trop

---

start.py

Sorterar listan av terminer så höstterminen kommer efter vårterminen i listan

Sort semester accordning vt and ht

---

js/csv_table_2_href.ts
templates/troop.html

Trying to fix the UTF-8 problem reported in #67

Add BOM-marker on xls export

---

README.md

Ett komplement till Windows och Linux.

Beskrivning av hur man startar på Mac

---

groupsummary.py
index.yaml
templates/groupsummary.html

Enligt reglerna på sidan för föreningsredovisning så står det att medlemmarna måste ha varit på minst 10 möten under året. 
"Som bidragsberättigad medlem räknas den som deltagit i föreningens planerade aktiviteter vid minst 10 tillfällen under året samt erlagt medlemsavgift på minst 100 kr."
Just nu så visas totalt antal aktiva medlemmar.
Denna fixa gör att antalet möten man varit på kollas. Visar fortfarande antalet medlemmar totalt inom parantes.

Uppdaterat åldersfördelningen så den stämmer med Göteborgs stads regler

---

templates/troop.html

Vet inte om detta är något som du vill ha på den delade setupen, men var en funktion som mina ledare önskade sig.
Som du ser kollar den var 3:e sekund om något möte är dirty och gör en sparning.

Auto save möten

---

data.py
lagerbidrag.py
scoutgroupinfo.py
start.py
templates/lagerbidrag.html
templates/scoutgroupinfo.html
templates/troop.html

Har gjort en första version för att ta fram lägerbidrag för göteborgs scoutdistrikt.
Har inte fått det bekräftat från dem ännu om de tycker designen är ok.
Men tänker det är bra om ni kan se koden redan nu.
man kanske vill lägga in någon mer beskrivning hur man ska söka bidraget och vad man kan fylla i för information på scoutkåren.

Lägerbidrag för göteborgs

---

lagerbidrag.py
start.py
templates/lagerbidrag.html
templates/lagerbidragform.html
templates/troop.html
templates/troops.html
templates/updatefromscoutnetform.html

Gjort det möjligt att söka bidrag från listan med avdelningar, inkluderar närvaron från alla avdelningar i lägerbidragsrapporten.
Validerar att man inte söker för mer än 14 dagar.

Möjlighet att söka lägerbidrag över flera avdelningar

---

dataimport.py

Number of persons to import was erroneously subtracted by one.

Correct number of persons imported printout

---

main.py
templates/start.html

Hade problem med att några använder inte hade de rättigheter som de borde. Se Issue #83. Efter att ha läst dokumentation lade jag därför till en logout-knapp och då kunde de starta om och få det att fungera. Känns som att det borde vara användbart för många att kunna logga ut, och även kunna byta användare i appen.

Lagt till logout-knapp

---

templates/lagerform.html
templates/meetingform.html
templates/troop.html

Även fixat lite problem med dubbla id:n och snyggat till layouten om man sitter vid en dator.

Lagt till hjälp vid uträkning av längd på möten

---

templates/meetingform.html

Changed meeting toggle to only change non-default values

---

appengine_config.py
coming.py
data.py
dataimport.py
excelreport.py
groupsummary.py
imports.py
ireport.py
jsonreport.py
lagerbidrag.py
main.py
persons.py
scoutgroupinfo.py
scoutnet.py
start.py

Cleaned up the imports:
* removed unsued imports
* replaced * with specifics
* replaced chained imports with origin, exemple: `from dataimport import nbd` 
* sorted imports

Remove unsued import, and sort the used import.

---

start.py

Clean up of start.py to get higher pylint score. Went from 5.39 to 9.44. To get further one must: break up show into muliple functions, remove 1-letter variable names, remove very long variable names.
Some overlap with PR #116.

start.py clean up

---

.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
admin.py
app.yaml
data.py
dataimport.py
imports.py
index.yaml
main.py
persons.py
progress.py
queue.yaml
scoutnet.py
scripts/download_data_from_prod.bat
scripts/run_local.bat
scripts/upload_data_to_dev.bat
start.py
templates/admin.html
templates/person.html
templates/progressreport.html
templates/update_person_ids.html

Implemented add person to scoutnet queue to use the returned member_no.
Implemented a migration script
You can not add a "local person", using personnr. You have to use add to scoutnet queue to get a member id.
Added information on missing add to scoutnet queue api-key.
Lots of optimizations to make the conversion to run quickly.
* Progress report nolonger stored in datastore. Using memcache to get better performance.
* Progress reporting was O(N^2) for number of report items. A cursor is used to only update new lines.
Moved admin utilities to new admin.py file
Moved progress related utilities to progress.py
Renamed importresult.html to progressreport.html
Add a link to scout group after import is done

Convert Person from id based on personnr to member_no

---

badge_templates/simbevis.json
badge_templates/yxbevis.json
badges.py
data_badge.py
start.py
templates/badge.html

Löser problemet med att ta bort ett märke för en avdelning #148
Löser problemet med att märkesURL inte blir kvar efter import från JSON.
Lägger till mallar för Yxa och Simning (behöver importeras som mallar)
Liten fix för läge med inga märken för avdelningar vid ny termin #147.
White space-förbättring för färre varningar

Fix remove troopbadge

---

templates/persons.html
templates/troops.html

Korrigerat felstavning i template/persons och template/troops för specifikt Göteborgs Kommun.
Fix #170

Rättning felstavning Kommunm
